### ISSUE TITLE
[Feature Request] Display answers based on CSS

### ISSUE THREAD

**Issue by kanjieater** [HelenFoster/KanjiVocab#13]
In relation to https://github.com/HelenFoster/KanjiVocab/issues/12

One possible solution would be to have only KanjiVocab and KanjiVocabExtra.

Then use CSS to toggle hiding the kanji, whether with visibility:none around the word or via a snippet like this:
![image](https://user-images.githubusercontent.com/32607317/58129787-31ce3880-7be0-11e9-9174-da9da718b59b.png)
```css

u, b {
    font-weight: normal;
  }
  
  u,
  b {
      text-decoration: none;
      color: #6abedb;
      font-weight: normal;
  }
  
  .front b {
  
     font-size: 0px;
  
   visibility: hidden;
  }
  
  .front b:after {
      background: #6abedb;
      border-radius: 5px;
    content:'X';
      font-size: 55px !important;
  
    visibility: visible;
    padding-left: 100px
  }

```
